ARG 	CHEMISTRY_PACKAGE=bbchem
FROM adoptopenjdk/maven-openjdk8 as builder

FROM 	builder as dependencies
ARG     CHEMISTRY_PACKAGE
ENV     CHEMISTRY_PACKAGE=${CHEMISTRY_PACKAGE}

FROM 	dependencies as jchem
ADD 	lib/jchem-16.4.25.0.jar /lib/jchem-16.4.25.0.jar
RUN     mvn install:install-file -Dfile=/lib/jchem-16.4.25.0.jar -DartifactId=jchem -DgroupId=com.chemaxon -Dversion=16.4.25.0 -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true

FROM 	dependencies as bbchem

FROM 	dependencies as indigo

FROM 	${CHEMISTRY_PACKAGE} as compile
ADD 	--chown=runner:runner pom.xml /src/pom.xml
WORKDIR /src
RUN 	mvn dependency:resolve -P ${CHEMISTRY_PACKAGE}
ADD 	. /src
RUN 	mvn clean && \
        mvn compile war:war -P ${CHEMISTRY_PACKAGE}
RUN     mv target/acas*.war /usr/local/tomcat/webapps/webapps/acas.war && \
        mv target/acas* /usr/local/tomcat/webapps/webapps/acas/

FROM tomcat:9.0.58-jre8-openjdk-slim-buster
RUN apt-get install -y openssl
COPY 	--chown=runner:runner --from=compile /usr/local/tomcat/webapps/acas.war /usr/local/tomcat/webapps/webapps/acas.war
COPY 	--chown=runner:runner --from=compile /usr/local/tomcat/webapps/acas /usr/local/tomcat/webapps/webapps/acas
WORKDIR $CATALINA_HOME
EXPOSE 	8080
ENV    ACAS_HOME=/home/runner/build
ENV    CATALINA_OPTS="-Xms512M -Xmx1536M -XX:MaxPermSize=512m"
COPY --chown=runner:runner ./PrepareConfigFiles.coffee /home/runner/build/src/javascripts/BuildUtilities/PrepareConfigFiles.coffee
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"] 
CMD 	["catalina.sh", "run"]
