// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.labseer.dto;

import com.labsynch.labseer.dto.MethodOptionDTO;

privileged aspect MethodOptionDTO_Roo_JavaBean {
    
    public String MethodOptionDTO.getMethod() {
        return this.method;
    }
    
    public void MethodOptionDTO.setMethod(String method) {
        this.method = method;
    }
    
}
