  CREATE TABLE "CRON_JOB" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(1,0) NOT NULL ENABLE, 
	"CODE_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"FUNCTION_NAME" VARCHAR2(255 CHAR), 
	"IGNORED" NUMBER(1,0) NOT NULL ENABLE, 
	"LAST_DURATION" NUMBER(19,0), 
	"LAST_RESULTJSON" CLOB, 
	"LAST_START_TIME" TIMESTAMP (6), 
	"NUMBER_OF_EXECUTIONS" NUMBER(10,0), 
	"RUN_USER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SCHEDULE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SCRIPT_FILE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SCRIPTJSONDATA" CLOB, 
	"SCRIPT_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" NUMBER(10,0), 
	 PRIMARY KEY ("ID"), 
	 UNIQUE ("CODE_NAME")
   );
   
   CREATE SEQUENCE  "CRON_JOB_PKSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

