DECLARE
  v_column_exists number := 0;
BEGIN
  SELECT COUNT(*) into v_column_exists
    FROM   USER_INDEXES
    WHERE  INDEX_NAME  IN('SUBJ_STATE_SUBJ_IDX', 'SUBJ_VAL_SUBJ_STATE_IDX', 'SUBJ_LBL_SUBJ_IDX');  
 IF (v_column_exists > 0) THEN
  dbms_output.put_line('INDEXES ALREADY EXIST');
 ELSE
     EXECUTE IMMEDIATE 'CREATE INDEX SUBJ_STATE_SUBJ_IDX ON SUBJECT_STATE (SUBJECT_ID)';
     EXECUTE IMMEDIATE 'CREATE INDEX SUBJ_VAL_SUBJ_STATE_IDX ON SUBJECT_VALUE (SUBJECT_STATE_ID)';
     EXECUTE IMMEDIATE 'CREATE INDEX SUBJ_LBL_SUBJ_IDX ON SUBJECT_LABEL (SUBJECT_ID)';
     dbms_output.put_line('CREATED INDEXES');
END IF;
END;