--------------------------------------------------------
--  DDL for Table ANALYSISGROUP_TREATMENTGROUP
--------------------------------------------------------

  CREATE TABLE "ANALYSISGROUP_TREATMENTGROUP" 
   (	"TREATMENT_GROUP_ID" NUMBER(19,0), 
	"ANALYSIS_GROUP_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ANALYSIS_GROUP
--------------------------------------------------------

  CREATE TABLE "ANALYSIS_GROUP" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table ANALYSIS_GROUP_LABEL
--------------------------------------------------------

  CREATE TABLE "ANALYSIS_GROUP_LABEL" 
   (	"ID" NUMBER(19,0), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"IMAGE_FILE" VARCHAR2(255 CHAR), 
	"LABEL_TEXT" VARCHAR2(255 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PHYSICALLY_LABLED" NUMBER(1,0), 
	"PREFERRED" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"ANALYSIS_GROUP_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ANALYSIS_GROUP_STATE
--------------------------------------------------------

  CREATE TABLE "ANALYSIS_GROUP_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"ANALYSIS_GROUP_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ANALYSIS_GROUP_VALUE
--------------------------------------------------------

  CREATE TABLE "ANALYSIS_GROUP_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"ANALYSIS_STATE_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table APPLICATION_SETTING
--------------------------------------------------------

  CREATE TABLE "APPLICATION_SETTING" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"PROP_NAME" VARCHAR2(255 CHAR), 
	"PROP_VALUE" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------

  CREATE TABLE "AUTHOR" 
   (	"ID" NUMBER(19,0), 
	"ACTIVATION_DATE" TIMESTAMP (6), 
	"ACTIVATION_KEY" VARCHAR2(255 CHAR), 
	"EMAIL_ADDRESS" VARCHAR2(255 CHAR), 
	"ENABLED" NUMBER(1,0), 
	"FIRST_NAME" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"LOCKED" NUMBER(1,0), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"USER_NAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table AUTHOR_ROLE
--------------------------------------------------------

  CREATE TABLE "AUTHOR_ROLE" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0), 
	"LSROLE_ID" NUMBER(19,0), 
	"AUTHOR_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table CODE_KIND
--------------------------------------------------------

  CREATE TABLE "CODE_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table CODE_ORIGIN
--------------------------------------------------------

  CREATE TABLE "CODE_ORIGIN" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(256 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table CODE_TYPE
--------------------------------------------------------

  CREATE TABLE "CODE_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(128 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table CONTAINER
--------------------------------------------------------

  CREATE TABLE "CONTAINER" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"LOCATION_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table CONTAINER_KIND
--------------------------------------------------------

  CREATE TABLE "CONTAINER_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table CONTAINER_LABEL
--------------------------------------------------------

  CREATE TABLE "CONTAINER_LABEL" 
   (	"ID" NUMBER(19,0), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"IMAGE_FILE" VARCHAR2(255 CHAR), 
	"LABEL_TEXT" VARCHAR2(255 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PHYSICALLY_LABLED" NUMBER(1,0), 
	"PREFERRED" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"CONTAINER_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table CONTAINER_STATE
--------------------------------------------------------

  CREATE TABLE "CONTAINER_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"CONTAINER_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table CONTAINER_TYPE
--------------------------------------------------------

  CREATE TABLE "CONTAINER_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(128 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table CONTAINER_VALUE
--------------------------------------------------------

  CREATE TABLE "CONTAINER_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"CONTAINER_STATE_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table DDICT_KIND
--------------------------------------------------------

  CREATE TABLE "DDICT_KIND" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DESCRIPTION" VARCHAR2(512 CHAR), 
	"DISPLAY_ORDER" NUMBER(10,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table DDICT_TYPE
--------------------------------------------------------

  CREATE TABLE "DDICT_TYPE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DESCRIPTION" VARCHAR2(512 CHAR), 
	"DISPLAY_ORDER" NUMBER(10,0), 
	"IGNORED" NUMBER(1,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table DDICT_VALUE
--------------------------------------------------------

  CREATE TABLE "DDICT_VALUE" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DESCRIPTION" VARCHAR2(512 CHAR), 
	"DISPLAY_ORDER" NUMBER(10,0), 
	"IGNORED" NUMBER(1,0), 
	"LABEL_TEXT" VARCHAR2(512 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"SHORT_NAME" VARCHAR2(256 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"SHORT_DESCRIPTION" VARCHAR2(1024 CHAR), 
	"PROTOCOL_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT_ANALYSISGROUP
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT_ANALYSISGROUP" 
   (	"ANALYSIS_GROUP_ID" NUMBER(19,0), 
	"EXPERIMENT_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT_KIND
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT_LABEL
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT_LABEL" 
   (	"ID" NUMBER(19,0), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"IMAGE_FILE" VARCHAR2(255 CHAR), 
	"LABEL_TEXT" VARCHAR2(255 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PHYSICALLY_LABLED" NUMBER(1,0), 
	"PREFERRED" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"EXPERIMENT_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT_STATE
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"EXPERIMENT_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT_TAG
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT_TAG" 
   (	"EXPERIMENT_ID" NUMBER(19,0), 
	"TAG_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(128 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table EXPERIMENT_VALUE
--------------------------------------------------------

  CREATE TABLE "EXPERIMENT_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"EXPERIMENT_STATE_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table FILE_THING
--------------------------------------------------------

  CREATE TABLE "FILE_THING" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"APPLICATION_TYPE" VARCHAR2(512 CHAR), 
	"DESCRIPTION" VARCHAR2(512 CHAR), 
	"FILE_EXTENSION" VARCHAR2(255 CHAR), 
	"FILE_SIZE" NUMBER(19,0), 
	"FILEURL" VARCHAR2(1024 CHAR), 
	"MIME_TYPE" VARCHAR2(512 CHAR), 
	"NAME" VARCHAR2(512 CHAR)
   );
--------------------------------------------------------
--  DDL for Table INTERACTION_KIND
--------------------------------------------------------

  CREATE TABLE "INTERACTION_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table INTERACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "INTERACTION_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(128 CHAR), 
	"TYPE_VERB" VARCHAR2(128 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_CONTAINER_CONTAINER
--------------------------------------------------------

  CREATE TABLE "ITX_CONTAINER_CONTAINER" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"FIRST_CONTAINER_ID" NUMBER(19,0), 
	"SECOND_CONTAINER_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_CONTAINER_CONTAINER_STATE
--------------------------------------------------------

  CREATE TABLE "ITX_CONTAINER_CONTAINER_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"ITX_CONTAINER_CONTAINER" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_CONTAINER_CONTAINER_VALUE
--------------------------------------------------------

  CREATE TABLE "ITX_CONTAINER_CONTAINER_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_STATE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_EXPT_EXPT
--------------------------------------------------------

  CREATE TABLE "ITX_EXPT_EXPT" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"FIRST_EXPERIMENT_ID" NUMBER(19,0), 
	"SECOND_EXPERIMENT_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_EXPT_EXPT_STATE
--------------------------------------------------------

  CREATE TABLE "ITX_EXPT_EXPT_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"ITX_EXPERIMENT_EXPERIMENT" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_EXPT_EXPT_VALUE
--------------------------------------------------------

  CREATE TABLE "ITX_EXPT_EXPT_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_STATE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_LS_THING_LS_THING
--------------------------------------------------------

  CREATE TABLE "ITX_LS_THING_LS_THING" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"FIRST_LS_THING_ID" NUMBER(19,0), 
	"SECOND_LS_THING_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_LS_THING_LS_THING_STATE
--------------------------------------------------------

  CREATE TABLE "ITX_LS_THING_LS_THING_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"ITX_LS_THING_LS_THING" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_LS_THING_LS_THING_VALUE
--------------------------------------------------------

  CREATE TABLE "ITX_LS_THING_LS_THING_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_STATE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_PROTOCOL_PROTOCOL
--------------------------------------------------------

  CREATE TABLE "ITX_PROTOCOL_PROTOCOL" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"FIRST_PROTOCOL_ID" NUMBER(19,0), 
	"SECOND_PROTOCOL_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_PROTOCOL_PROTOCOL_STATE
--------------------------------------------------------

  CREATE TABLE "ITX_PROTOCOL_PROTOCOL_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"ITX_PROTOCOL_PROTOCOL" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_PROTOCOL_PROTOCOL_VALUE
--------------------------------------------------------

  CREATE TABLE "ITX_PROTOCOL_PROTOCOL_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_STATE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_SUBJECT_CONTAINER
--------------------------------------------------------

  CREATE TABLE "ITX_SUBJECT_CONTAINER" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"CONTAINER_ID" NUMBER(19,0), 
	"SUBJECT_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_SUBJECT_CONTAINER_STATE
--------------------------------------------------------

  CREATE TABLE "ITX_SUBJECT_CONTAINER_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"ITX_SUBJECT_CONTAINER" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table ITX_SUBJECT_CONTAINER_VALUE
--------------------------------------------------------

  CREATE TABLE "ITX_SUBJECT_CONTAINER_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_STATE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table LABEL_KIND
--------------------------------------------------------

  CREATE TABLE "LABEL_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table LABEL_SEQUENCE
--------------------------------------------------------

  CREATE TABLE "LABEL_SEQUENCE" 
   (	"ID" NUMBER(19,0), 
	"DIGITS" NUMBER(10,0), 
	"GROUP_DIGITS" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LABEL_PREFIX" VARCHAR2(50 CHAR), 
	"LABEL_SEPARATOR" VARCHAR2(10 CHAR), 
	"LABEL_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"LATEST_NUMBER" NUMBER(19,0), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"THING_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LABEL_TYPE
--------------------------------------------------------

  CREATE TABLE "LABEL_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LSTHING_TAG
--------------------------------------------------------

  CREATE TABLE "LSTHING_TAG" 
   (	"LSTHING_ID" NUMBER(19,0), 
	"TAG_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table LS_INTERACTION
--------------------------------------------------------

  CREATE TABLE "LS_INTERACTION" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"FIRST_THING_ID" NUMBER(19,0), 
	"SECOND_THING_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table LS_ROLE
--------------------------------------------------------

  CREATE TABLE "LS_ROLE" 
   (	"ID" NUMBER(19,0), 
	"ROLE_DESCRIPTION" VARCHAR2(200 CHAR), 
	"ROLE_NAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_ANL_GRP
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_ANL_GRP" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_CONTAINER
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_CONTAINER" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_EXPT
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_EXPT" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_ITX_CNTR_CNTR
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_ITX_CNTR_CNTR" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_ITX_PROTOCOL_PROTOCOL
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_ITX_PROTOCOL_PROTOCOL" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_ITX_SUBJ_CNTR
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_ITX_SUBJ_CNTR" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_PROTOCOL
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_PROTOCOL" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_SUBJECT
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_SUBJECT" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_SEQ_TRT_GRP
--------------------------------------------------------

  CREATE TABLE "LS_SEQ_TRT_GRP" 
   (	"ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_TAG
--------------------------------------------------------

  CREATE TABLE "LS_TAG" 
   (	"ID" NUMBER(19,0), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"TAG_TEXT" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_THING
--------------------------------------------------------

  CREATE TABLE "LS_THING" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LS_THING_LABEL
--------------------------------------------------------

  CREATE TABLE "LS_THING_LABEL" 
   (	"ID" NUMBER(19,0), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"IMAGE_FILE" VARCHAR2(255 CHAR), 
	"LABEL_TEXT" VARCHAR2(255 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PHYSICALLY_LABLED" NUMBER(1,0), 
	"PREFERRED" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"LS_THING_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"LSTHING_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table LS_THING_STATE
--------------------------------------------------------

  CREATE TABLE "LS_THING_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"LSTHING_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table LS_THING_VALUE
--------------------------------------------------------

  CREATE TABLE "LS_THING_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LSTHING_STATE_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table LS_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "LS_TRANSACTION" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table OPERATOR_KIND
--------------------------------------------------------

  CREATE TABLE "OPERATOR_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table OPERATOR_TYPE
--------------------------------------------------------

  CREATE TABLE "OPERATOR_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(25 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table PROTOCOL
--------------------------------------------------------

  CREATE TABLE "PROTOCOL" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"SHORT_DESCRIPTION" VARCHAR2(1000 CHAR)
   );
--------------------------------------------------------
--  DDL for Table PROTOCOL_KIND
--------------------------------------------------------

  CREATE TABLE "PROTOCOL_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table PROTOCOL_LABEL
--------------------------------------------------------

  CREATE TABLE "PROTOCOL_LABEL" 
   (	"ID" NUMBER(19,0), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"IMAGE_FILE" VARCHAR2(255 CHAR), 
	"LABEL_TEXT" VARCHAR2(255 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PHYSICALLY_LABLED" NUMBER(1,0), 
	"PREFERRED" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"PROTOCOL_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table PROTOCOL_STATE
--------------------------------------------------------

  CREATE TABLE "PROTOCOL_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"PROTOCOL_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table PROTOCOL_TAG
--------------------------------------------------------

  CREATE TABLE "PROTOCOL_TAG" 
   (	"PROTOCOL_ID" NUMBER(19,0), 
	"TAG_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table PROTOCOL_TYPE
--------------------------------------------------------

  CREATE TABLE "PROTOCOL_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(128 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table PROTOCOL_VALUE
--------------------------------------------------------

  CREATE TABLE "PROTOCOL_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"PROTOCOL_STATE_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table STATE_KIND
--------------------------------------------------------

  CREATE TABLE "STATE_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table STATE_TYPE
--------------------------------------------------------

  CREATE TABLE "STATE_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(64 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "SUBJECT" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table SUBJECT_LABEL
--------------------------------------------------------

  CREATE TABLE "SUBJECT_LABEL" 
   (	"ID" NUMBER(19,0), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"IMAGE_FILE" VARCHAR2(255 CHAR), 
	"LABEL_TEXT" VARCHAR2(255 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PHYSICALLY_LABLED" NUMBER(1,0), 
	"PREFERRED" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"SUBJECT_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table SUBJECT_STATE
--------------------------------------------------------

  CREATE TABLE "SUBJECT_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"SUBJECT_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table SUBJECT_VALUE
--------------------------------------------------------

  CREATE TABLE "SUBJECT_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"SUBJECT_STATE_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table THING_KIND
--------------------------------------------------------

  CREATE TABLE "THING_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table THING_PAGE
--------------------------------------------------------

  CREATE TABLE "THING_PAGE" 
   (	"ID" NUMBER(19,0), 
	"ARCHIVED" NUMBER(1,0), 
	"CURRENT_EDITOR" VARCHAR2(255 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PAGE_CONTENT" CLOB, 
	"PAGE_NAME" VARCHAR2(255 CHAR), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"THING_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table THING_PAGE_ARCHIVE
--------------------------------------------------------

  CREATE TABLE "THING_PAGE_ARCHIVE" 
   (	"ID" NUMBER(19,0), 
	"ARCHIVED" NUMBER(1,0), 
	"CURRENT_EDITOR" VARCHAR2(255 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PAGE_CONTENT" CLOB, 
	"PAGE_NAME" VARCHAR2(255 CHAR), 
	"PAGE_VERSION" NUMBER(10,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"THING_ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table THING_TYPE
--------------------------------------------------------

  CREATE TABLE "THING_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(128 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table TREATMENTGROUP_SUBJECT
--------------------------------------------------------

  CREATE TABLE "TREATMENTGROUP_SUBJECT" 
   (	"SUBJECT_ID" NUMBER(19,0), 
	"TREATMENT_GROUP_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table TREATMENT_GROUP
--------------------------------------------------------

  CREATE TABLE "TREATMENT_GROUP" 
   (	"ID" NUMBER(19,0), 
	"CODE_NAME" VARCHAR2(255 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(255 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table TREATMENT_GROUP_LABEL
--------------------------------------------------------

  CREATE TABLE "TREATMENT_GROUP_LABEL" 
   (	"ID" NUMBER(19,0), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"IMAGE_FILE" VARCHAR2(255 CHAR), 
	"LABEL_TEXT" VARCHAR2(255 CHAR), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PHYSICALLY_LABLED" NUMBER(1,0), 
	"PREFERRED" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"TREATMENT_GROUP_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table TREATMENT_GROUP_STATE
--------------------------------------------------------

  CREATE TABLE "TREATMENT_GROUP_STATE" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"DELETED" NUMBER(1,0), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0), 
	"TREATMENT_GROUP_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table TREATMENT_GROUP_VALUE
--------------------------------------------------------

  CREATE TABLE "TREATMENT_GROUP_VALUE" 
   (	"ID" NUMBER(19,0), 
	"BLOB_VALUE" BLOB, 
	"CLOB_VALUE" CLOB, 
	"CODE_KIND" VARCHAR2(255 CHAR), 
	"CODE_ORIGIN" VARCHAR2(255 CHAR), 
	"CODE_TYPE" VARCHAR2(255 CHAR), 
	"CODE_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"CODE_VALUE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"CONC_UNIT" VARCHAR2(25 CHAR), 
	"CONCENTRATION" FLOAT(126), 
	"DATE_VALUE" TIMESTAMP (6), 
	"DELETED" NUMBER(1,0), 
	"FILE_VALUE" VARCHAR2(512 CHAR), 
	"IGNORED" NUMBER(1,0), 
	"LS_KIND" VARCHAR2(255 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"LS_TYPE" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(350 CHAR), 
	"MODIFIED_BY" VARCHAR2(255 CHAR), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"NUMBER_OF_REPLICATES" NUMBER(10,0), 
	"NUMERIC_VALUE" NUMBER(38,18), 
	"OPERATOR_KIND" VARCHAR2(10 CHAR), 
	"OPERATOR_TYPE" VARCHAR2(25 CHAR), 
	"OPERATOR_TYPE_AND_KIND" VARCHAR2(50 CHAR), 
	"PUBLIC_DATA" NUMBER(1,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"SIG_FIGS" NUMBER(10,0), 
	"STRING_VALUE" VARCHAR2(255 CHAR), 
	"UNCERTAINTY" NUMBER(38,18), 
	"UNCERTAINTY_TYPE" VARCHAR2(255 CHAR), 
	"UNIT_KIND" VARCHAR2(25 CHAR), 
	"UNIT_TYPE" VARCHAR2(25 CHAR), 
	"UNIT_TYPE_AND_KIND" VARCHAR2(55 CHAR), 
	"URL_VALUE" VARCHAR2(2000 CHAR), 
	"VERSION" NUMBER(10,0), 
	"TREATMENT_STATE_ID" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table UNCERTAINTY_KIND
--------------------------------------------------------

  CREATE TABLE "UNCERTAINTY_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table UNIT_KIND
--------------------------------------------------------

  CREATE TABLE "UNIT_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table UNIT_TYPE
--------------------------------------------------------

  CREATE TABLE "UNIT_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(64 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table UPDATE_LOG
--------------------------------------------------------

  CREATE TABLE "UPDATE_LOG" 
   (	"ID" NUMBER(19,0), 
	"COMMENTS" VARCHAR2(512 CHAR), 
	"LS_TRANSACTION" NUMBER(19,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6), 
	"THING" NUMBER(19,0), 
	"UPDATE_ACTION" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table VALUE_KIND
--------------------------------------------------------

  CREATE TABLE "VALUE_KIND" 
   (	"ID" NUMBER(19,0), 
	"KIND_NAME" VARCHAR2(64 CHAR), 
	"LS_TYPE_AND_KIND" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	"LS_TYPE" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table VALUE_TYPE
--------------------------------------------------------

  CREATE TABLE "VALUE_TYPE" 
   (	"ID" NUMBER(19,0), 
	"TYPE_NAME" VARCHAR2(64 CHAR), 
	"VERSION" NUMBER(10,0)
   );
