DECLARE
  v_column_exists number := 0;
BEGIN
  SELECT COUNT(*) into v_column_exists
    FROM   USER_INDEXES
    WHERE  INDEX_NAME  IN('ITX_LS_THING_LS_THNG_FRST_IDX', 'ITX_LS_THING_LS_THNG_SCND_IDX', 'ITX_THNG_THNG_STATE_THNG_IDX','ITX_THNG_THNG_VAL_STATE_IDX');  
 IF (v_column_exists > 0) THEN
  dbms_output.put_line('INDEXES ALREADY EXIST');
 ELSE
     EXECUTE IMMEDIATE 'CREATE INDEX ITX_LS_THING_LS_THNG_FRST_IDX ON ITX_LS_THING_LS_THING (FIRST_LS_THING_ID)';
     EXECUTE IMMEDIATE 'CREATE INDEX ITX_LS_THING_LS_THNG_SCND_IDX ON ITX_LS_THING_LS_THING (SECOND_LS_THING_ID)';
     EXECUTE IMMEDIATE 'CREATE INDEX ITX_THNG_THNG_STATE_THNG_IDX ON ITX_LS_THING_LS_THING_STATE (ITX_LS_THING_LS_THING)';
     EXECUTE IMMEDIATE 'CREATE INDEX ITX_THNG_THNG_VAL_STATE_IDX ON ITX_LS_THING_LS_THING_VALUE (LS_STATE)';
     dbms_output.put_line('CREATED INDEXES');
END IF;
END;