
  CREATE TABLE "ACAS"."TEMP_SELECT_TABLE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"LS_TRANSACTION" NUMBER(19,0), 
	"NUMBER_VAR" NUMBER(19,0), 
	"RECORDED_BY" VARCHAR2(255 CHAR), 
	"RECORDED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"STRING_VAR" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,0), 
	 PRIMARY KEY ("ID")
   );
   
  CREATE SEQUENCE  "ACAS"."TEMP_SELECT_PKSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


  CREATE INDEX "ACAS"."TEMP_SELECT_NUMBER_IDX" ON "ACAS"."TEMP_SELECT_TABLE" ("NUMBER_VAR") ;

  CREATE INDEX "ACAS"."TEMP_SELECT_STRING_IDX" ON "ACAS"."TEMP_SELECT_TABLE" ("STRING_VAR");

  CREATE INDEX "ACAS"."TEMP_SELECT_TRXN_IDX" ON "ACAS"."TEMP_SELECT_TABLE" ("LS_TRANSACTION");
