SELECT lo_unlink(blob_value::int) FROM analysis_group_value;
--SELECT lo_unlink(blob_value::int) FROM author_value;
SELECT lo_unlink(blob_value::int) FROM container_value;
SELECT lo_unlink(blob_value::int) FROM experiment_value;
SELECT lo_unlink(blob_value::int) FROM itx_container_container_value;
SELECT lo_unlink(blob_value::int) FROM itx_expt_expt_value;
SELECT lo_unlink(blob_value::int) FROM itx_ls_thing_ls_thing_value;
SELECT lo_unlink(blob_value::int) FROM itx_protocol_protocol_value;
SELECT lo_unlink(blob_value::int) FROM itx_subject_container_value;
SELECT lo_unlink(blob_value::int) FROM ls_thing_value;
SELECT lo_unlink(blob_value::int) FROM protocol_value;
SELECT lo_unlink(blob_value::int) FROM subject_value;
SELECT lo_unlink(blob_value::int) FROM treatment_group_value;

ALTER TABLE analysis_group_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
--ALTER TABLE author_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE container_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE experiment_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE itx_container_container_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE itx_expt_expt_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE itx_ls_thing_ls_thing_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE itx_protocol_protocol_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE itx_subject_container_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE ls_thing_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE protocol_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE subject_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;
ALTER TABLE treatment_group_value ALTER COLUMN blob_value SET DATA TYPE bytea USING blob_value_temp;

ALTER TABLE analysis_group_value DROP COLUMN blob_value_temp;
--ALTER TABLE author_value DROP COLUMN blob_value_temp;
ALTER TABLE container_value DROP COLUMN blob_value_temp;
ALTER TABLE experiment_value DROP COLUMN blob_value_temp;
ALTER TABLE itx_container_container_value DROP COLUMN blob_value_temp;
ALTER TABLE itx_expt_expt_value DROP COLUMN blob_value_temp;
ALTER TABLE itx_ls_thing_ls_thing_value DROP COLUMN blob_value_temp;
ALTER TABLE itx_protocol_protocol_value DROP COLUMN blob_value_temp;
ALTER TABLE itx_subject_container_value DROP COLUMN blob_value_temp;
ALTER TABLE ls_thing_value DROP COLUMN blob_value_temp;
ALTER TABLE protocol_value DROP COLUMN blob_value_temp;
ALTER TABLE subject_value DROP COLUMN blob_value_temp;
ALTER TABLE treatment_group_value DROP COLUMN blob_value_temp;