// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.labseer.domain;

import com.labsynch.labseer.chemclasses.CmpdRegMolecule.RegistrationStatus;
import com.labsynch.labseer.chemclasses.CmpdRegMolecule.StandardizationStatus;
import com.labsynch.labseer.domain.AbstractBBChemStructure;
import java.util.BitSet;
import java.util.Date;
import java.util.HashMap;

privileged aspect AbstractBBChemStructure_Roo_JavaBean {
    
    public String AbstractBBChemStructure.getPreReg() {
        return this.preReg;
    }
    
    public void AbstractBBChemStructure.setPreReg(String preReg) {
        this.preReg = preReg;
    }
    
    public String AbstractBBChemStructure.getReg() {
        return this.reg;
    }
    
    public void AbstractBBChemStructure.setReg(String reg) {
        this.reg = reg;
    }
    
    public String AbstractBBChemStructure.getMol() {
        return this.mol;
    }
    
    public void AbstractBBChemStructure.setMol(String mol) {
        this.mol = mol;
    }
    
    public BitSet AbstractBBChemStructure.getSubstructure() {
        return this.substructure;
    }
    
    public void AbstractBBChemStructure.setSubstructure(BitSet substructure) {
        this.substructure = substructure;
    }
    
    public BitSet AbstractBBChemStructure.getSimilarity() {
        return this.similarity;
    }
    
    public void AbstractBBChemStructure.setSimilarity(BitSet similarity) {
        this.similarity = similarity;
    }
    
    public Date AbstractBBChemStructure.getRecordedDate() {
        return this.recordedDate;
    }
    
    public void AbstractBBChemStructure.setRecordedDate(Date recordedDate) {
        this.recordedDate = recordedDate;
    }
    
    public StandardizationStatus AbstractBBChemStructure.getStandardizationStatus() {
        return this.standardizationStatus;
    }
    
    public void AbstractBBChemStructure.setStandardizationStatus(StandardizationStatus standardizationStatus) {
        this.standardizationStatus = standardizationStatus;
    }
    
    public String AbstractBBChemStructure.getStandardizationComment() {
        return this.standardizationComment;
    }
    
    public void AbstractBBChemStructure.setStandardizationComment(String standardizationComment) {
        this.standardizationComment = standardizationComment;
    }
    
    public RegistrationStatus AbstractBBChemStructure.getRegistrationStatus() {
        return this.registrationStatus;
    }
    
    public void AbstractBBChemStructure.setRegistrationStatus(RegistrationStatus registrationStatus) {
        this.registrationStatus = registrationStatus;
    }
    
    public String AbstractBBChemStructure.getRegistrationComment() {
        return this.registrationComment;
    }
    
    public void AbstractBBChemStructure.setRegistrationComment(String registrationComment) {
        this.registrationComment = registrationComment;
    }
    
    public Double AbstractBBChemStructure.getExactMolWeight() {
        return this.exactMolWeight;
    }
    
    public void AbstractBBChemStructure.setExactMolWeight(Double exactMolWeight) {
        this.exactMolWeight = exactMolWeight;
    }
    
    public Double AbstractBBChemStructure.getAverageMolWeight() {
        return this.averageMolWeight;
    }
    
    public void AbstractBBChemStructure.setAverageMolWeight(Double averageMolWeight) {
        this.averageMolWeight = averageMolWeight;
    }
    
    public Integer AbstractBBChemStructure.getTotalCharge() {
        return this.totalCharge;
    }
    
    public void AbstractBBChemStructure.setTotalCharge(Integer totalCharge) {
        this.totalCharge = totalCharge;
    }
    
    public String AbstractBBChemStructure.getSmiles() {
        return this.smiles;
    }
    
    public void AbstractBBChemStructure.setSmiles(String smiles) {
        this.smiles = smiles;
    }
    
    public String AbstractBBChemStructure.getInchi() {
        return this.inchi;
    }
    
    public void AbstractBBChemStructure.setInchi(String inchi) {
        this.inchi = inchi;
    }
    
    public String AbstractBBChemStructure.getMolecularFormula() {
        return this.molecularFormula;
    }
    
    public void AbstractBBChemStructure.setMolecularFormula(String molecularFormula) {
        this.molecularFormula = molecularFormula;
    }
    
    public HashMap<String, String> AbstractBBChemStructure.getProperties() {
        return this.properties;
    }
    
    public void AbstractBBChemStructure.setProperties(HashMap<String, String> properties) {
        this.properties = properties;
    }
    
}
