// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.labseer.domain;

import com.labsynch.labseer.domain.ChemStructure;
import javax.persistence.Entity;

privileged aspect ChemStructure_Roo_Jpa_Entity {
    
    declare @type: ChemStructure: @Entity;
    
    public ChemStructure.new() {
        super();
    }

}
