// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.labseer.domain;

import com.labsynch.labseer.domain.InteractionKind;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect InteractionKind_Roo_Configurable {
    
    declare @type: InteractionKind: @Configurable;
    
}
