// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.labseer.domain;

import com.labsynch.labseer.domain.UnitType;

privileged aspect UnitType_Roo_JavaBean {
    
    public String UnitType.getTypeName() {
        return this.typeName;
    }
    
    public void UnitType.setTypeName(String typeName) {
        this.typeName = typeName;
    }
    
}
