// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.labseer.chemclasses.bbchem;

import com.labsynch.labseer.chemclasses.bbchem.BBChemStandardizationDryRunStructure;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BBChemStandardizationDryRunStructure_Roo_Jpa_ActiveRecord {
    
    public static final List<String> BBChemStandardizationDryRunStructure.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static long BBChemStandardizationDryRunStructure.countBBChemStandardizationDryRunStructures() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BBChemStandardizationDryRunStructure o", Long.class).getSingleResult();
    }
    
    public static List<BBChemStandardizationDryRunStructure> BBChemStandardizationDryRunStructure.findAllBBChemStandardizationDryRunStructures() {
        return entityManager().createQuery("SELECT o FROM BBChemStandardizationDryRunStructure o", BBChemStandardizationDryRunStructure.class).getResultList();
    }
    
    public static List<BBChemStandardizationDryRunStructure> BBChemStandardizationDryRunStructure.findAllBBChemStandardizationDryRunStructures(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BBChemStandardizationDryRunStructure o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BBChemStandardizationDryRunStructure.class).getResultList();
    }
    
    public static BBChemStandardizationDryRunStructure BBChemStandardizationDryRunStructure.findBBChemStandardizationDryRunStructure(Long id) {
        if (id == null) return null;
        return entityManager().find(BBChemStandardizationDryRunStructure.class, id);
    }
    
    public static List<BBChemStandardizationDryRunStructure> BBChemStandardizationDryRunStructure.findBBChemStandardizationDryRunStructureEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BBChemStandardizationDryRunStructure o", BBChemStandardizationDryRunStructure.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<BBChemStandardizationDryRunStructure> BBChemStandardizationDryRunStructure.findBBChemStandardizationDryRunStructureEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BBChemStandardizationDryRunStructure o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BBChemStandardizationDryRunStructure.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public BBChemStandardizationDryRunStructure BBChemStandardizationDryRunStructure.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BBChemStandardizationDryRunStructure merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
