// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.labsynch.labseer.domain;

import com.labsynch.labseer.domain.LabelSequence;
import com.labsynch.labseer.domain.LabelSequenceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LabelSequenceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LabelSequenceDataOnDemand: @Component;
    
    private Random LabelSequenceDataOnDemand.rnd = new SecureRandom();
    
    private List<LabelSequence> LabelSequenceDataOnDemand.data;
    
    public LabelSequence LabelSequenceDataOnDemand.getNewTransientLabelSequence(int index) {
        LabelSequence obj = new LabelSequence();
        setDbSequence(obj, index);
        setDigits(obj, index);
        setGroupDigits(obj, index);
        setIgnored(obj, index);
        setLabelPrefix(obj, index);
        setLabelSeparator(obj, index);
        setLabelTypeAndKind(obj, index);
        setModifiedDate(obj, index);
        setStartingNumber(obj, index);
        setThingTypeAndKind(obj, index);
        return obj;
    }
    
    public void LabelSequenceDataOnDemand.setDbSequence(LabelSequence obj, int index) {
        String dbSequence = "dbSequence_" + index;
        obj.setDbSequence(dbSequence);
    }
    
    public void LabelSequenceDataOnDemand.setDigits(LabelSequence obj, int index) {
        Integer digits = new Integer(index);
        obj.setDigits(digits);
    }
    
    public void LabelSequenceDataOnDemand.setGroupDigits(LabelSequence obj, int index) {
        Boolean groupDigits = true;
        obj.setGroupDigits(groupDigits);
    }
    
    public void LabelSequenceDataOnDemand.setIgnored(LabelSequence obj, int index) {
        Boolean ignored = true;
        obj.setIgnored(ignored);
    }
    
    public void LabelSequenceDataOnDemand.setLabelPrefix(LabelSequence obj, int index) {
        String labelPrefix = "labelPrefix_" + index;
        if (labelPrefix.length() > 50) {
            labelPrefix = labelPrefix.substring(0, 50);
        }
        obj.setLabelPrefix(labelPrefix);
    }
    
    public void LabelSequenceDataOnDemand.setLabelSeparator(LabelSequence obj, int index) {
        String labelSeparator = "labelSep_" + index;
        if (labelSeparator.length() > 10) {
            labelSeparator = labelSeparator.substring(0, 10);
        }
        obj.setLabelSeparator(labelSeparator);
    }
    
    public void LabelSequenceDataOnDemand.setLabelTypeAndKind(LabelSequence obj, int index) {
        String labelTypeAndKind = "labelTypeAndKind_" + index;
        if (labelTypeAndKind.length() > 255) {
            labelTypeAndKind = labelTypeAndKind.substring(0, 255);
        }
        obj.setLabelTypeAndKind(labelTypeAndKind);
    }
    
    public void LabelSequenceDataOnDemand.setModifiedDate(LabelSequence obj, int index) {
        Date modifiedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setModifiedDate(modifiedDate);
    }
    
    public void LabelSequenceDataOnDemand.setStartingNumber(LabelSequence obj, int index) {
        Long startingNumber = new Integer(index).longValue();
        obj.setStartingNumber(startingNumber);
    }
    
    public void LabelSequenceDataOnDemand.setThingTypeAndKind(LabelSequence obj, int index) {
        String thingTypeAndKind = "thingTypeAndKind_" + index;
        if (thingTypeAndKind.length() > 255) {
            thingTypeAndKind = thingTypeAndKind.substring(0, 255);
        }
        obj.setThingTypeAndKind(thingTypeAndKind);
    }
    
    public LabelSequence LabelSequenceDataOnDemand.getSpecificLabelSequence(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LabelSequence obj = data.get(index);
        Long id = obj.getId();
        return LabelSequence.findLabelSequence(id);
    }
    
    public LabelSequence LabelSequenceDataOnDemand.getRandomLabelSequence() {
        init();
        LabelSequence obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return LabelSequence.findLabelSequence(id);
    }
    
    public boolean LabelSequenceDataOnDemand.modifyLabelSequence(LabelSequence obj) {
        return false;
    }
    
    public void LabelSequenceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LabelSequence.findLabelSequenceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LabelSequence' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LabelSequence>();
        for (int i = 0; i < 10; i++) {
            LabelSequence obj = getNewTransientLabelSequence(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
