name: Create mirrored base branches

on:
  push:
    branches: [ "**" ]
  create:
    tags: "**"
  workflow_dispatch:
jobs:
  mirror-base-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        acas-repo: [ acas, acasclient, racas ]
    steps:
      - name: Set ACAS_REF to the current branch ${{ github.ref }}
        run: |
          echo "ACAS_REF=$(echo ${{ github.ref }} | sed 's/refs\/heads\///g')" >> $GITHUB_ENV
      - name: Check if branch exists
        env: 
          GITHUB_TOKEN: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
        uses: actions/github-script@v6
        with:
          script: |
            response = await github.rest.git.getRef({
              owner: 'mcneilco',
              repo: "${{ matrix.acas-repo }}",
              ref: "${{ github.ref }}"
            })
            console.log(response);
        continue-on-error: true
      - name: Checkout ACAS
        uses: actions/checkout@v3
        with:
          repository: mcneilco/${{ matrix.acas-repo }}
          path: acas
      # - name: Create new branch in 
      #   env: 
      #     GITHUB_TOKEN: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
      #   run: |
      #     octokit.rest.git.createRef({
      #         owner: 'mcneilco',
      #         repo: 'acas',
      #         ref: "${{ github.ref }}",
      #         sha,
      #     });