name: Create mirrored base branches

on:
  push:
    branches: [ "**" ]
  create:
    tags: "**"
  workflow_dispatch:
jobs:
  mirror-base-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        acas-repo: [ acas, acasclient, racas ]
    steps:
      - name: Set ACAS_REF to the current branch ${{ github.ref }}
        run: |
          echo "ACAS_REF=$(echo ${{ github.ref }} | sed 's/refs\/heads\///g')" >> $GITHUB_ENV
      - name: Check if branch exists
        env: 
          GITHUB_TOKEN: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
        uses: actions/github-script@v6
        id: branch-exists
        with:
          script: |
            try {
              response = await github.rest.git.getRef({
                owner: 'mcneilco',
                repo: "${{ matrix.acas-repo }}",
                ref: "heads/${{ env.ACAS_REF }}"
              })
            } catch (e) {
                return false
            }
            return true
        continue-on-error: true
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get closest release branch name
        # if: ${{steps.branch-exists.outputs.result == false}}
        id: get-closest-release-branch
        run: |
          search="release"

          # Get most recent commit with a release branch
          commit=$(git log --decorate \
            | grep 'commit' \
            | grep "origin/$search" \
            | head -n 1 \
            | awk '{ print $2 }' \
            | tr -d "\n")

          # Fetch the release by matching the search pattern, grabbing the branch names
          match=refs/remotes/origin/$search/
          release_refs_with_commit=$(git show-ref \
            | grep $commit \
            | grep $match \
            | awk '{ print $2 }' \
            | sed  "s~$match~~g")

          # If more than one release matches commit then sort by semver (desc) e.g. 2023.1.0, 2023.0.0, 2022.0.0 and pick 20223.1.0
          release_name=$search/$(echo "$release_refs_with_commit" | sort -t. -k 1,1nr -k 2,2nr -k 3,3nr -k 4,4nr | head -n1)
          echo "Closest release branch: $release_name"
          echo ::set-output name=release-branch-name::$release_name
      - name: Create new branch in repo mcneilco/${{ matrix.acas-repo }} from branch ${{ steps.get-closest-release-branch.outputs.release-branch-name}}
        env: 
          GITHUB_TOKEN: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
        uses: actions/github-script@v6
        with:
          script: |
            try {
              response = await github.rest.git.getRef({
                owner: 'mcneilco',
                repo: "${{ matrix.acas-repo }}",
                ref: "${{ steps.get-closest-release-branch.outputs.release-branch-name}}"
              })
            } catch (e) {
                console.log(e)
            }
            return true
        continue-on-error: true

      # - name: Create branch 
      #   uses: actions/checkout@v3
      #   with:
      #     repository: mcneilco/${{ matrix.acas-repo }}
      #     path: ${{ matrix.acas-repo }}
      #     ref: "${{ steps.get-closest-release-branch.outputs.release-branch-name}}"
      # # - name: Create new branch in 
      # #   env: 
      # #     GITHUB_TOKEN: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
      # #   working-directory: acas
      # #   run: |
      # #     git checkout -b ${{env.ACAS_REF}}