name: Create mirrored base branches

on:
  push:
    branches: [ "**" ]
  create:
    tags: "**"
  workflow_dispatch:
jobs:
  mirror-base-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        acas-repo: [ acas, acasclient, racas ]
    steps:
      - name: Set ACAS_REF to the current branch ${{ github.ref }}
        run: |
          echo "ACAS_REF=$(echo ${{ github.ref }} | sed 's/refs\/heads\///g')" >> $GITHUB_ENV
      - name: Check if branch exists
        uses: actions/github-script@v6
        id: get_branch_otherrepo
        with:
          route: GET /repos/cneilco/${{ matrix.acas-repo }}/${{ env.ACAS_REF }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
        continue-on-error: true
      - name: Checkout ACAS
        uses: actions/checkout@v3
        with:
          repository: mcneilco/${{ matrix.acas-repo }}
          path: acas
      - name: Create new branch in 
        env: 
          gITHUB_TOKEN: ${{ secrets.ACAS_WORKFLOWS_TOKEN }}
        run: |
          if [[ '${{ steps.get_branch_otherrepo.outputs.status }}' = '200' ]]; then
            OTHERREPO_BRANCH="${{ steps.extract-branch.outputs.branch }}"
          else
            OTHERREPO_BRANCH=master
          fi
          echo "Otherrepo branch for checkout: $OTHERREPO_BRANCH"
          echo "OTHERREPO_BRANCH=$OTHERREPO_BRANCH" >> $GITHUB_ENV