name: Dale Docker Image

on:
  push

env:
  CACHE_NUMBER: 1  # increase to reset cache manually

jobs:
  acas-roo-server:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chemistry_package: [ indigo, bbchem ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      # Dependency Caching Steps
      # Standard Java Workflow Steps
      - uses: actions/checkout@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Cache Save and Restore
      - name: Java Dependency Cache Step
        uses: actions/cache@v2.1.4
        with:
          path: .m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ env.CACHE_NUMBER }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository }}-oss
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.chemistry_package }}
            type=ref,event=pr,suffix=-${{ matrix.chemistry_package }}
            type=ref,event=tag,suffix=-${{ matrix.chemistry_package }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile-multistage
          platforms: linux/amd64,linux/arm64/v8
          build-args: CHEMISTRY_PACKAGE=${{ matrix.chemistry_package }}
